### ISSUE TITLE
scripts/osx_package.sh typo on line 11

### ISSUE THREAD

**Issue by dishadc** [96jonesa/AutoBought#29]
There is a typo on line 11 of the scripts/osx_package.sh script that causes it to fail. 
Line 11 is currently `cp scripts/ox_start.sh AutoBoughtPackage/osx_start.sh`
It should be changed to: `cp scripts/osx_start.sh AutoBoughtPackage/osx_start.sh`

**Comment by 96jonesa** [comment]
thanks for pointing this out! struggling to test on osx as our only mac owner is out of disk space, so this slipped by. will fix asap

**Comment by 96jonesa** [comment]
@dishadc fixed
